### ISSUE TITLE
Unable to execute a single test in latest IntelliJ (13.1.2)

### ISSUE THREAD

**Issue by michaeladler** [TNG/junit-dataprovider#18]
Since the latest update of IntelliJ (13.1.2), I can no longer execute a single test within a class. 

Example:

```java
import org.junit.Test;
import org.junit.runner.RunWith;

import com.tngtech.java.junit.dataprovider.DataProvider;
import com.tngtech.java.junit.dataprovider.DataProviderRunner;
import com.tngtech.java.junit.dataprovider.UseDataProvider;

@RunWith(DataProviderRunner.class)
public class ExampleTest {

    @DataProvider
    public static Object[][] exampleProvider() {

        return new Object[][] {{"foo"}};
    }

    @Test
    @UseDataProvider("exampleProvider")
    public void testSomething(String input) {}

}
```
Below is the exception I get when trying to execute the test:

```java
java.lang.Exception: No tests found matching Method testSomething(ExampleTest) from org.junit.internal.requests.ClassRequest@4c032069
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```
However, executing the whole test class works. I'm not sure if this can be fixed in the junit-dataprovider.

**Comment by spaceCamel** [comment]
I'm having this issue with IntelliJ IDEA 14 CE (14.0.1 and 14.1.4); junit-dataprovider 1.9.4; junit 4.12;

```
java.lang.Exception: No tests found matching Method testMethodName(com.company.MyTest) from org.junit.internal.requests.ClassRequest@2ac1fdc4
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

```
RunWith(DataProviderRunner.class)
public class MyTest
{
    @Test
    @UseDataProvider(value = "data_table")
    public void testMethodName(String input)
    { ... }

    @DataProvider
    public static List<List<Object>> data_table()
    { ... }
}
```

**Comment by aaschmid** [comment]
Hi @spaceCamel,

thanks for reporting this. Can you please open a new issue if the exception is still raised? For me, though, the following example works using junit-dataprovider [v1.9.4](https://github.com/TNG/junit-dataprovider/releases/tag/v1.9.4) and IntelliJ IDEA 14.1.3:

```java
package com.tngtech.test.java.junit.dataprovider;

import com.tngtech.java.junit.dataprovider.DataProvider;
import com.tngtech.java.junit.dataprovider.DataProviderRunner;
import com.tngtech.java.junit.dataprovider.UseDataProvider;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@RunWith(DataProviderRunner.class)
public class MyTest {

    @Test
    @UseDataProvider(value = "data_table")
    public void testMethodName(String input) {
        System.out.println(input);
    }

    @DataProvider
    public static List<List<Object>> data_table() {
        return Arrays.asList(
                Arrays.<Object>asList("test1"),
                Arrays.<Object>asList("test2")
            );
    }
}
```
using junit-dataprovider [v1.9.4](https://github.com/TNG/junit-dataprovider/releases/tag/v1.9.4) and IntelliJ IDEA 14.1.3 works perfectly, hence I cannot reproduce this issue.



Regards,
Andreas
