### ISSUE TITLE
NullPointerException when toString() of parameter returns null

### ISSUE THREAD

**Issue by PascalSchumacher** [TNG/junit-dataprovider#66]
Hi,

thanks for providing junit-dataprovider.

While working on a pull request to switch assertj from JUnitParams to junit-dataprovider I encountered the this problem.

When I try to use null as a parameter, e.g.:

```java
  @DataProvider()
  public static Object[][] testDescriptionGenerator() {
    return new Object[][] {
        { new TestDescription(null) }
  }

  @Test
  @UseDataProvider("testDescriptionGenerator")
  public void should_return_empty_String(TestDescription testDescription) {
    assertThat(formatter.format(testDescription)).isEmpty();
  }
```

I get 
```
java.lang.NullPointerException
	at com.tngtech.java.junit.dataprovider.internal.placeholder.ParameterPlaceholder.format(ParameterPlaceholder.java:99)
	at com.tngtech.java.junit.dataprovider.internal.placeholder.ParameterPlaceholder.formatAll(ParameterPlaceholder.java:70)
	at com.tngtech.java.junit.dataprovider.internal.placeholder.ParameterPlaceholder.getReplacementFor(ParameterPlaceholder.java:57)
	at com.tngtech.java.junit.dataprovider.internal.placeholder.BasePlaceholder.process(BasePlaceholder.java:61)
	at com.tngtech.java.junit.dataprovider.DataProviderFrameworkMethod.getName(DataProviderFrameworkMethod.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.testName(BlockJUnit4ClassRunner.java:225)
	at org.junit.runners.BlockJUnit4ClassRunner.describeChild(BlockJUnit4ClassRunner.java:96)
	at org.junit.runners.BlockJUnit4ClassRunner.describeChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:85)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Because  in this case TestDescription#toString returns null. Not sure if this is something that junit-dataprovider should handle?

**Comment by aaschmid** [comment]
Hi @PascalSchumacher, the problem is really that ```TestDescription#toString()``` returns ```null``` as the junit-dataprovider ```ParameterPlaceholder``` line 93 to 99 are 

```
        String result;
        if (param instanceof String) {
            result = (String) param;
        } else {
            result = param.toString();
        }
        return result.replaceAll("\\r", "\\\\r").replaceAll("\\n", "\\\\n");
```

I will fix it in a moment :-)
Thanks for reporting this!

**Comment by aaschmid** [comment]
Is it somehow urgent? I can provide you a snapshot version to retest if you want. Otherwise I can create a new release hopefully before christmas. What would you prefer @PascalSchumacher?

**Comment by aaschmid** [comment]
Btw. second commit suppresses findbugs warning because findbugs assumes that ```toString()``` does not return ```null``` :-S

**Comment by PascalSchumacher** [comment]
Thanks for the ultra quick fix. :+1: 

Yes, returning `null` from toString() is not a good practice.

>Is it somehow urgent? I can provide you a snapshot version to retest if you want. Otherwise I can >create a new release hopefully before christmas. What would you prefer @PascalSchumacher?

Thanks for the offer, but it's not urgent so I'm fine with waiting.
