### ISSUE TITLE
Can not use list as parameter?

### ISSUE THREAD

**Issue by PascalSchumacher** [TNG/junit-dataprovider#77]
I would like to use a `List` as a parameter, e.g.:

```java
@DataProvider
public static Object[][] stringsData() {
    return new Object[][] {
        { Arrays.asList("string1", "stringValue"), "stringValue" }
    };
}

@Test
@DataProvider("stringsData")
public void test(List<String> strings, String expectedValue) {
}
```

but this results in

```
java.lang.Error: Exception while exploding 'Tesst' using its '@DataProvider' due to: Test method expected  1 parameters but got 1 from @DataProvider row 0
	at com.tngtech.java.junit.dataprovider.internal.TestGenerator.generateExplodedTestMethodsFor(TestGenerator.java:57)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner.generateExplodedTestMethodsFor(DataProviderRunner.java:206)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner.computeTestMethods(DataProviderRunner.java:158)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner.validateInstanceMethods(DataProviderRunner.java:98)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
Caused by: java.lang.IllegalArgumentException: Test method expected  1 parameters but got 1 from @DataProvider row 0
	at com.tngtech.java.junit.dataprovider.internal.convert.StringConverter.checkArgumentsAndParameterCount(StringConverter.java:80)
	at com.tngtech.java.junit.dataprovider.internal.convert.StringConverter.convert(StringConverter.java:45)
	at com.tngtech.java.junit.dataprovider.internal.DataConverter.convert(DataConverter.java:102)
	at com.tngtech.java.junit.dataprovider.internal.TestGenerator.explodeTestMethod(TestGenerator.java:108)
	at com.tngtech.java.junit.dataprovider.internal.TestGenerator.explodeTestMethod(TestGenerator.java:103)
	at com.tngtech.java.junit.dataprovider.internal.TestGenerator.generateExplodedTestMethodsFor(TestGenerator.java:55)
	... 26 more
```

I'm I doing something wrong or is it not possible to use a `List` as a parameter? Are there any workarounds?

Thanks,
Pascal

**Comment by PascalSchumacher** [comment]
It was my fault. I annotated the `test` method with `@DataProvider` instead of `@UseDataProvider`. :(

Sorry for the noise.

**Comment by aaschmid** [comment]
Hi @PascalSchumacher, the problem is, that you use 

```
@DataProvider("stringsData")
```

must be

```
@UseDataProvider("stringsData")
```

Hint: with version 1.10.4, you can also leave out the method name  ```("stringsData")```.

**Comment by aaschmid** [comment]
Oh, you saw it yourself and no problem for the noise :-)
